[Grid]
X1-grid    0  @resx1@  @lx1@
X2-grid    0  @resx2@  @lx2@
X3-grid    0  @resx3@  @lx3@

[Physics]
rhs hydro

[TimeIntegrator]
method  rk3
cfl   0.5
tstop 10.0

[Hydro]
viscosity  0.0001

[InitFlow]
shear_layer 0.25 1.0
large_scale_2d_noise 1.0  0.1 # Amplitude and cut-off length
#mean_field 0.0 0.0 1.0 # Mean velocity in each direction

[Output]
vtk 100.0
vtk_dir vtk
