[Grid]
X1-grid    0.0  64  1.0
X2-grid    0.0  2  1.0
X3-grid    0.0  2  1.0

[Physics]
rhs advection

[TimeIntegrator]
method  rk3
cfl   0.5
tstop 1.0

[Advection]
direction  1
velocity  1.0

[InitFlow]
large_scale_noise 1.0  0.1 # Amplitude and cut-off length
#mean_field 0.0 0.0 1.0 # Mean velocity in each direction

[Output]
vtk 1.0
vtk_dir vtk