[Grid]
X1-grid    -0.5  256  0.5
X2-grid    -0.5  256  0.5
X3-grid    -0.5  2  0.5

[Physics]
rhs hydro
viscosity  0.0001

[TimeIntegrator]
method  rk3
cfl   0.5
tstop 1.0

[InitFlow]
shear_layer 0.25 1.0
large_scale_2d_noise 1.0  0.1 # Amplitude and cut-off length
#mean_field 0.0 0.0 1.0 # Mean velocity in each direction

[Output]
vtk 0.1
vtk_dir vtk
