name: Build documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master # Run on PRs targeting master
  push:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - name: install python dependencies
        run: python -m pip install --exists-action=w --no-cache-dir -r doc/python_requirements.txt
      - name: compile documentation
        run: python -m sphinx -T -W -b html -d _build/doctrees -D language=en doc/source _build
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: '_build'
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Deploy only for master
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
