on:
  workflow_call:
    inputs:
      TEST_OPTIONS:
        required: true
        type: string

# concurrency:
#   # auto-cancel any concurrent job *in the same context*
#   # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
#   # see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

env:
  TEST_OPTIONS: ${{ inputs.TEST_OPTIONS }}
  PYTHONPATH: ${{ github.workspace }}
  ASTRA_DIR: ${{ github.workspace }}

permissions: {}

jobs:
  Serial:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.3
        with:
          submodules: recursive
          persist-credentials: false
      - name: Python packages
        uses: ./.github/workflows/pre-install-py-packages
      - name: Build
        run: |
          source .venv/bin/activate
          mkdir -p job-serial
          cd job-serial
          python3 ../test/test.py build $TEST_OPTIONS
      - name: Advection tests
        run: |
          source .venv/bin/activate
          cd job-serial
          python3 ../test/test.py run advection $TEST_OPTIONS
      - name: Hydro tests
        run: |
          source .venv/bin/activate
          cd job-serial
          python3 ../test/test.py run shearing_wave $TEST_OPTIONS
      - name: MHD tests
        run: |
          source .venv/bin/activate
          cd job-serial
          python3 ../test/test.py run shearing_wave_mhd $TEST_OPTIONS
      - name: Compressible hydro tests
        run: |
          source .venv/bin/activate
          cd job-serial
          python3 ../test/test.py run shearing_wave_compressible $TEST_OPTIONS

  Parallel:
    runs-on: self-hosted
    needs: Serial
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.3
        with:
          submodules: recursive
          persist-credentials: false
      - name: Python packages
        uses: ./.github/workflows/pre-install-py-packages
      - name: Build
        run: |
          source .venv/bin/activate
          mkdir -p job-parallel
          cd job-parallel
          python3 ../test/test.py build $TEST_OPTIONS -mpi
      - name: Unit tests
        run: |
          source .venv/bin/activate
          cd job-parallel
          mpirun -np 4 ./build/astra -test
      - name: Advection tests
        run: |
          source .venv/bin/activate
          cd job-parallel
          python3 ../test/test.py run advection $TEST_OPTIONS -mpi
      - name: Hydro tests
        run: |
          source .venv/bin/activate
          cd job-parallel
          python3 ../test/test.py run shearing_wave $TEST_OPTIONS -mpi
      - name: MHD tests
        run: |
          source .venv/bin/activate
          cd job-parallel
          python3 ../test/test.py run shearing_wave_mhd $TEST_OPTIONS -mpi
      - name: Compressible hydro tests
        run: |
          source .venv/bin/activate
          cd job-parallel
          python3 ../test/test.py run shearing_wave_compressible $TEST_OPTIONS -mpi
